sudo: required
language: bash
services:
  - docker
stages:
  - test
  - release
  - publish
jobs:
  include:
    - stage: test
      script:
        - docker build ./tests
        - ./test
    - stage: publish
      script:
        - docker build -t next .
        - docker run next